apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual # will be used to bind PersistentVolumeClaim requests to this PersistentVolume.
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: "Retain"
  hostPath:
    path: "/home/vv/code_projects/kube1/data"